{% set name = "icepapcms" %}
{% set version = "3.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icepapcms-{{ version }}.tar.gz
  sha256: 11f509955dd475227594e36b68ac75b94e9a0a17f0e26734dd2cdd57e3ecf4ae

build:
  number: 0
  noarch: python
  entry_points:
    - icepapcms = icepapcms.__main__:main
    - ipapconsole = icepapcms.gui.ipapconsole:main
    - icepapsnapshot = icepapcms.lib.snapshot:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - configobj
    - icepap >=3.7.0
    - ipy >=0.62
    - ldap3
    - pyqt >=5.12.3
    - python >={{ python_min }}
    - pyyaml
    - storm >=0.23
    # for pkg_resources
    - setuptools

test:
  imports:
    - icepapcms
    - icepapcms.gui
    - icepapcms.gui.icepapcms
    - icepapcms.gui.ipapconsole
    - icepapcms.lib
  commands:
    - pip check
    - icepapcms --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/IcepapCMS
  summary: Icepap Configuration Management System and Test Tool
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beenje
    - perhedmax
    - rhomspuron
